name: Lint and Test

on:
  # Trigger the workflow on push or pull request,
  # but push action is only for the feature branch
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
  push:
    branches-ignore:
      - develop
      - 'release/**'
jobs:
  lint_and_test:
    name: Static code analysis and unit test
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Bangkok

      - uses: actions/checkout@v2.3.2

      - name: Load Gradle cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Archive Detekt report
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report
          path: build/reports/detekt/

      - name: Run Unit Tests & Jacoco
        run: ./gradlew jacocoTestReport

      # Archive Unit test & code coverage report
      - name: Archive Code coverage report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: code-coverage-report
          path: |
            app/build/reports/
            data/build/reports/jacoco/jacocoTestReport/
