name: Code analysis and unit tests

on:
  # Trigger this workflow for all push actions
  # except those in develop, main, or release branch,
  # and pull request actions
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
  push:
    branches-ignore:
      - develop
      - main
      - 'release/**'
jobs:
  code_analysis_and_unit_tests:
    name: Static code analysis and unit tests
    runs-on: self-hosted
    strategy:
      matrix:
        api-level: [ 30 ]
        target: [ google_apis ]
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v2.3.4

      - name: Load cached Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          # Currently set to default value
          upload-chunk-size: 33554432

      # Run Detekt & archive Detekt reports
      - name: Run Detekt on CoroutineTemplate
        working-directory: ./CoroutineTemplate
        run: ./gradlew detekt

      - name: Run Detekt on RxJavaTemplate
        working-directory: ./RxJavaTemplate
        run: ./gradlew detekt

      - name: Archive Detekt report on CoroutineTemplate
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report-coroutine
          path: CoroutineTemplate/build/reports/detekt/

      - name: Archive Detekt reports on RxJavaTemplate
        uses: actions/upload-artifact@v2
        with:
          name: detekt-reports-rxjava
          path: RxJavaTemplate/build/reports/detekt/

      # Run unit tests & Jacoco for code coverage & archive reports
      - name: Run unit tests & Jacoco on RxJavaTemplate
        working-directory: ./RxJavaTemplate
        run: ./gradlew jacocoTestReport

      - name: Archive code coverage reports on RxJavaTemplate
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-reports-rxjava
          path: |
            RxJavaTemplate/app/build/reports/jacoco/jacocoTestReport/
            RxJavaTemplate/data/build/reports/jacoco/jacocoTestReport/
