name: Code Analysis and Tests

on:
  # Trigger this workflow for all push actions,
  # except those in develop, main, or release branch
  push:
    branches-ignore:
      - develop
      - main
      - 'release/**'
jobs:
  code_analysis_and_tests:
    name: Static code analysis and tests
    runs-on: self-hosted
    strategy:
      matrix:
        api-level: [ 30 ]
        target: [ google_apis ]
    steps:
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v2.3.4

      - name: Load Gradle cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          upload-chunk-size: 33554432

      # Run Detekt and Archive Detekt reports
      - name: Run Detekt on CoroutineTemplate
        working-directory: ./CoroutineTemplate
        run: ./gradlew detekt

      - name: Run Detekt on RxJavaTemplate
        working-directory: ./RxJavaTemplate
        run: ./gradlew detekt

      - name: Archive Detekt report on CoroutineTemplate
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report-coroutine
          path: CoroutineTemplate/build/reports/detekt/

      - name: Archive Detekt reports on RxJavaTemplate
        uses: actions/upload-artifact@v2
        with:
          name: detekt-reports-rxjava
          path: RxJavaTemplate/build/reports/detekt/

      # Run unit tests & Jacoco for code coverage & Archive reports
      - name: Run unit tests & Jacoco on RxJavaTemplate
        working-directory: ./RxJavaTemplate
        run: ./gradlew jacocoTestReport

      - name: Archive code coverage reports on RxJavaTemplate
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-reports-rxjava
          path: |
            RxJavaTemplate/app/build/reports/jacoco/jacocoTestReport/
            RxJavaTemplate/data/build/reports/jacoco/jacocoTestReport/

      # Set up AVD snapshot caching
      - name: Load AVD cached
        id: avd-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}
          upload-chunk-size: 33554432

      - name: Create AVD & Generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          force-avd-creation: false
          working-directory: ./RxJavaTemplate
          script: echo "Generated AVD snapshot for caching."

      # Run UI tests & Archive reports
      - name: Run UI tests on RxJavaTemplate
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          force-avd-creation: false
          working-directory: ./RxJavaTemplate
          script: ./gradlew connectedCheck

      - name: Archive UI test reports on RxJavaTemplate
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ui-test-reports-rxjava
          path: RxJavaTemplate/app/build/reports/androidTests/connected/
