name: Deploy staging

on:
  # Only trigger this workflow on push action in develop branch
  push:
    branches:
      - develop
jobs:
  run_tests_and_deploy_staging:
    name: Run tests and deploy staging
    runs-on: self-hosted
    strategy:
      matrix:
        api-level: [ 30 ]
        target: [ google_apis ]
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v2.3.4

      - name: Load cached Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          # Currently set to default value
          upload-chunk-size: 33554432

      # Run Detekt & archive Detekt reports
      - name: Run Detekt on CoroutineTemplate
        working-directory: ./CoroutineTemplate
        run: ./gradlew detekt

      - name: Run Detekt on RxJavaTemplate
        working-directory: ./RxJavaTemplate
        run: ./gradlew detekt

      - name: Archive Detekt report on CoroutineTemplate
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report-coroutine
          path: CoroutineTemplate/build/reports/detekt/

      - name: Archive Detekt reports on RxJavaTemplate
        uses: actions/upload-artifact@v2
        with:
          name: detekt-reports-rxjava
          path: RxJavaTemplate/build/reports/detekt/

      # Run unit tests & Jacoco for code coverage & archive reports
      - name: Run unit tests & Jacoco on RxJavaTemplate
        working-directory: ./RxJavaTemplate
        run: ./gradlew jacocoTestReport

      - name: Archive code coverage reports on RxJavaTemplate
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-reports-rxjava
          path: |
            RxJavaTemplate/app/build/reports/jacoco/jacocoTestReport/
            RxJavaTemplate/data/build/reports/jacoco/jacocoTestReport/

      # Set up AVD snapshot caching
      - name: Load cached AVD
        id: avd-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}
          # Currently set to default value
          upload-chunk-size: 33554432

      - name: Create AVD & generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          force-avd-creation: false
          working-directory: ./RxJavaTemplate
          script: echo "Generated AVD snapshot for caching."

      # Run UI tests & archive reports
      - name: Run UI tests on RxJavaTemplate
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          force-avd-creation: false
          working-directory: ./RxJavaTemplate
          script: ./gradlew connectedCheck

      - name: Archive UI test reports on RxJavaTemplate
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ui-test-reports-rxjava
          path: RxJavaTemplate/app/build/reports/androidTests/connected/

      # Build staging debug artifacts
      - name: Build CoroutineTemplate artifact
        working-directory: ./CoroutineTemplate
        run: ./gradlew assembleStagingDebug

      - name: Build RxJavaTemplate artifact
        working-directory: ./RxJavaTemplate
        run: ./gradlew assembleStagingDebug

      # Upload artifacts to GitHub
      - name: Upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: staging-debug-artifacts
          path: |
            RxJavaTemplate/app/build/outputs/apk/staging/debug/app-staging-debug.apk
            CoroutineTemplate/app/build/outputs/apk/staging/debug/app-staging-debug.apk
