name: Lint and Test

# Choose the branch or branches you want to run this workflow
on: push
jobs:
  lint_and_test:
    name: Static code analysis and unit test
    runs-on: self-hosted
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v2.3.4

      - name: Load Gradle cached
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          upload-chunk-size: 20000000

      # Run Detekt and Archive Detekt reports
      - name: Run Detekt on CoroutineTemplate
        working-directory: ./CoroutineTemplate
        run: ./gradlew detekt

      - name: Run Detekt on RxJavaTemplate
        working-directory: ./RxJavaTemplate
        run: ./gradlew detekt

      - name: Archive Detekt report on CoroutineTemplate
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report-coroutine
          path: CoroutineTemplate/build/reports/detekt/

      - name: Archive Detekt report on RxJavaTemplate
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report-rxjava
          path: RxJavaTemplate/build/reports/detekt/

      # Run Unit Test & Jacoco for code coverage & Archive reports
      - name: Run Unit Tests & Jacoco on RxJavaTemplate
        working-directory: ./RxJavaTemplate
        run: ./gradlew jacocoTestReport

      - name: Archive Code coverage report on RxJavaTemplate
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report-rxjava
          path: |
            RxJavaTemplate/app/build/reports/jacoco/jacocoTestReport/
            RxJavaTemplate/data/build/reports/jacoco/jacocoTestReport/
